import { ReadingExercise } from "./data";

export const LESEN_EXERCISES_T2: ReadingExercise[] = [
  {
    id: "lesen-mc-4",
    title: "Teil 2: Leben ohne Auto in der Stadt",
    level: "B1",
    topic: "Umwelt & Verkehr",
    duration: "15 Phút",
    type: "Trắc nghiệm",
    questionType: "multiple_choice",
    readingText: `Tageszeitung: Immer mehr deutsche Großstädte wie Hamburg, Berlin und München versuchen seit einigen Jahren aktiv, den Autoverkehr in ihren dicht besiedelten Innenstädten drastisch zu reduzieren. Der Hauptgrund für diese drastischen Maßnahmen ist nicht nur der tägliche, frustrierende Stau im Berufsverkehr, sondern vor allem die extrem hohe Luftverschmutzung, die gesundheitliche Probleme für die Anwohner verursacht. 

Einige Stadtviertel wurden bereits erfolgreich in sogenannte autofreie Zonen umgewandelt. Das bedeutet, dass dort nur noch Fußgänger, Radfahrer und der öffentliche Nahverkehr wie Busse und Straßenbahnen erlaubt sind. Anwohner, die dringend ein Auto benötigen, müssen auf Carsharing-Angebote zurückgreifen oder ihre privaten Fahrzeuge am Stadtrand in teuren Parkhäusern abstellen. 

Laut einer kürzlich veröffentlichten Umfrage des Umweltamtes finden 60 Prozent der Stadtbewohner diese neue Entwicklung sehr gut. Sie genießen die ungewohnte Ruhe, die saubere Luft und den neu gewonnenen Platz auf den Straßen, wo Kinder nun sicherer spielen können. Es gibt jedoch auch massive Kritik, vor allem von älteren Menschen und lokalen Geschäftsleuten. Viele Ladenbesitzer berichten besorgt, dass ihre Umsätze um bis zu 20 Prozent gesunken seien, da Kunden, die von außerhalb kommen, nun nicht mehr direkt vor dem Geschäft parken können und deshalb lieber in Einkaufszentren am Stadtrand fahren. Verkehrsexperten raten den Städten daher, als Ausgleich den öffentlichen Nahverkehr deutlich billiger oder sogar komplett kostenlos zu machen, um die Innenstädte attraktiv zu halten.`,
    questions: [
      { id: 1, question: "Warum wollen Großstädte weniger Autos in der Innenstadt?", options: ["A) Weil es nicht genug Parkplätze für alle Autos gibt.", "B) Vor allem wegen der schlechten Luft und dem vielen Stau.", "C) Weil sie Platz für neue, große Einkaufszentren brauchen."], correct: "B) Vor allem wegen der schlechten Luft und dem vielen Stau.", explanation: "Der Hauptgrund... ist nicht nur der tägliche... Stau, sondern vor allem die extrem hohe Luftverschmutzung. (Lý do chính không chỉ là tắc đường hàng ngày mà chủ yếu là do ô nhiễm không khí cực kỳ cao.)" },
      { id: 2, question: "Wer darf in den sogenannten 'autofreien Zonen' noch fahren?", options: ["A) Nur Anwohner mit spezieller Erlaubnis.", "B) Nur Geschäftsleute, die Waren liefern.", "C) Fahrräder, Busse, Straßenbahnen und Fußgänger."], correct: "C) Fahrräder, Busse, Straßenbahnen und Fußgänger.", explanation: "...dass dort nur noch Fußgänger, Radfahrer und der öffentliche Nahverkehr wie Busse und Straßenbahnen erlaubt sind. (...rằng ở đó chỉ có người đi bộ, người đi xe đạp và phương tiện công cộng như xe buýt, tàu điện được phép hoạt động.)" },
      { id: 3, question: "Wo müssen private Autos in diesen Zonen geparkt werden?", options: ["A) Direkt vor den Wohnhäusern.", "B) In teuren Parkhäusern am Stadtrand.", "C) In den Innenhöfen der Geschäfte."], correct: "B) In teuren Parkhäusern am Stadtrand.", explanation: "...ihre privaten Fahrzeuge am Stadtrand in teuren Parkhäusern abstellen. (...đỗ xe cá nhân của họ ở vùng ven thành phố trong những nhà để xe đắt đỏ.)" },
      { id: 4, question: "Wie reagiert die Mehrheit der Stadtbewohner auf die neuen Zonen?", options: ["A) 60 Prozent der Bewohner finden die Entwicklung gut.", "B) Die meisten Bewohner wollen sofort aufs Land ziehen.", "C) Fast alle Bewohner protestieren gegen die autofreien Zonen."], correct: "A) 60 Prozent der Bewohner finden die Entwicklung gut.", explanation: "Laut einer... Umfrage... finden 60 Prozent der Stadtbewohner diese neue Entwicklung sehr gut. (Theo một cuộc khảo sát, 60% cư dân thành phố đánh giá diễn biến mới này là rất tốt.)" },
      { id: 5, question: "Wer kritisiert die autofreien Zonen am stärksten?", options: ["A) Kinder und Jugendliche.", "B) Ältere Menschen und lokale Geschäftsleute.", "C) Die Politiker der Großstädte."], correct: "B) Ältere Menschen und lokale Geschäftsleute.", explanation: "Es gibt jedoch auch massive Kritik, vor allem von älteren Menschen und lokalen Geschäftsleuten. (Tuy nhiên cũng có nhiều sự chỉ trích gay gắt, đặc biệt từ người cao tuổi và các chủ doanh nghiệp địa phương.)" },
      { id: 6, question: "Was empfehlen Verkehrsexperten den Städten?", options: ["A) Sie sollten mehr Parkhäuser in der Innenstadt bauen.", "B) Sie sollten den öffentlichen Nahverkehr billiger oder kostenlos machen.", "C) Sie sollten das Autofahren wieder für alle erlauben."], correct: "B) Sie sollten den öffentlichen Nahverkehr billiger oder kostenlos machen.", explanation: "Verkehrsexperten raten den Städten daher, als Ausgleich den öffentlichen Nahverkehr deutlich billiger oder sogar komplett kostenlos zu machen... (Các chuyên gia giao thông khuyên các thành phố nên giảm giá mạnh hoặc miễn phí hoàn toàn phương tiện công cộng để bù đắp...)" }
    ]
  },
  {
    id: "lesen-mc-5",
    title: "Teil 2: Vegetarismus bei Jugendlichen",
    level: "B1",
    topic: "Gesundheit & Ernährung",
    duration: "15 Phút",
    type: "Trắc nghiệm",
    questionType: "multiple_choice",
    readingText: `Magazin für Ernährung: In deutschen Schulhöfen und Kantinen ist ein deutlicher Wandel zu beobachten. Immer mehr Jugendliche in Deutschland verzichten ganz bewusst auf Fleisch und entscheiden sich für eine vegetarische oder sogar streng vegane Ernährung. Aktuelle Statistiken zeigen, dass bereits rund 15 Prozent der 15- bis 20-Jährigen sich komplett vegetarisch ernähren – das ist eine Verdopplung im Vergleich zum letzten Jahrzehnt. 

Die Gründe für diese weitreichende Entscheidung sind sehr unterschiedlich, aber oft stark von Emotionen und Verantwortungsbewusstsein geprägt. Viele Teenager geben in Interviews an, dass sie aus tiefer Tierliebe kein Fleisch mehr essen möchten, nachdem sie im Internet Dokumentationen über die schrecklichen Bedingungen in der Massentierhaltung gesehen haben. Für andere steht hingegen der Klimaschutz im absoluten Vordergrund, da die Produktion von Fleisch enorm viel Wasser verbraucht und große Mengen an schädlichen Treibhausgasen produziert. Der gesundheitliche Aspekt, wie etwa das Abnehmen, spielt bei den jungen Leuten laut Umfragen interessanterweise nur eine eher kleine Nebenrolle.

Diese rasante Entwicklung stellt viele Eltern und Schulen vor unerwartete Herausforderungen. Oft wissen Mütter und Väter am Anfang nicht, was sie für ihre Kinder kochen sollen, um einen Nährstoffmangel, insbesondere bei Eisen und Vitamin B12, zu vermeiden. Mediziner warnen davor, einfach nur das Fleisch wegzulassen; stattdessen müssten vermehrt Bohnen, Linsen und Nüsse auf dem Speiseplan stehen. Einige moderne Schulen haben bereits hervorragend reagiert und bieten in der Mittagspause täglich mindestens zwei attraktive vegetarische Gerichte an, die auch bei Nicht-Vegetariern sehr beliebt sind.`,
    questions: [
      { id: 1, question: "Was besagt die aktuelle Statistik über Jugendliche?", options: ["A) Fast alle Jugendlichen essen mittlerweile täglich Fleisch.", "B) Etwa 15 Prozent der Jugendlichen essen kein Fleisch mehr.", "C) Jugendliche essen heute doppelt so viel Fleisch wie früher."], correct: "B) Etwa 15 Prozent der Jugendlichen essen kein Fleisch mehr.", explanation: "...dass bereits rund 15 Prozent der 15- bis 20-Jährigen sich komplett vegetarisch ernähren. (...rằng khoảng 15% giới trẻ từ 15-20 tuổi hiện đang ăn chay hoàn toàn.)" },
      { id: 2, question: "Welche Gründe nennen viele Teenager für den Fleischverzicht?", options: ["A) Sie haben Dokumentationen über Massentierhaltung gesehen.", "B) Sie finden, dass Fleisch im Supermarkt zu teuer ist.", "C) Ihre Eltern zwingen sie dazu, vegetarisch zu leben."], correct: "A) Sie haben Dokumentationen über Massentierhaltung gesehen.", explanation: "...dass sie aus tiefer Tierliebe kein Fleisch mehr essen möchten, nachdem sie... Dokumentationen über die schrecklichen Bedingungen in der Massentierhaltung gesehen haben. (...sau khi họ xem các phim tài liệu về điều kiện kinh khủng trong ngành chăn nuôi công nghiệp.)" },
      { id: 3, question: "Warum verzichten einige Jugendliche wegen des Klimas auf Fleisch?", options: ["A) Weil Tiere in der Natur weniger Platz brauchen als Autos.", "B) Weil die Fleischproduktion viel Wasser verbraucht und Treibhausgase verursacht.", "C) Weil vegetarisches Essen nicht so heiß gekocht werden muss."], correct: "B) Weil die Fleischproduktion viel Wasser verbraucht und Treibhausgase verursacht.", explanation: "...da die Produktion von Fleisch enorm viel Wasser verbraucht und große Mengen an schädlichen Treibhausgasen produziert. (...vì việc sản xuất thịt tiêu thụ lượng nước khổng lồ và thải ra một lượng lớn khí nhà kính độc hại.)" },
      { id: 4, question: "Welche Rolle spielt die Gesundheit (z.B. Abnehmen) für die Jugendlichen?", options: ["A) Es ist der mit Abstand wichtigste Grund.", "B) Es spielt eine sehr große Rolle.", "C) Es spielt nur eine eher kleine Nebenrolle."], correct: "C) Es spielt nur eine eher kleine Nebenrolle.", explanation: "Der gesundheitliche Aspekt, wie etwa das Abnehmen, spielt... interessanterweise nur eine eher kleine Nebenrolle. (Khía cạnh sức khỏe, ví dụ như giảm cân, điều thú vị là chỉ đóng một vai trò phụ khá nhỏ.)" },
      { id: 5, question: "Welches Problem haben einige Eltern am Anfang?", options: ["A) Sie wissen nicht, was sie ohne Fleisch kochen sollen.", "B) Sie wollen nicht getrennt von ihren Kindern essen.", "C) Sie finden kein vegetarisches Essen im Supermarkt."], correct: "A) Sie wissen nicht, was sie ohne Fleisch kochen sollen.", explanation: "Oft wissen Mütter und Väter am Anfang nicht, was sie für ihre Kinder kochen sollen... (Thường thì các ông bố bà mẹ lúc đầu không biết nên nấu món gì cho con...)" },
      { id: 6, question: "Was raten Mediziner jungen Vegetariern?", options: ["A) Sie sollten einfach das Fleisch beim Essen auf dem Teller lassen.", "B) Sie sollten mehr Bohnen, Linsen und Nüsse essen, um Nährstoffmangel zu vermeiden.", "C) Sie sollten zusätzlich viel Kuhmilch trinken."], correct: "B) Sie sollten mehr Bohnen, Linsen und Nüsse essen, um Nährstoffmangel zu vermeiden.", explanation: "Mediziner warnen davor, einfach nur das Fleisch wegzulassen; stattdessen müssten vermehrt Bohnen, Linsen und Nüsse auf dem Speiseplan stehen. (Bác sĩ khuyên không nên chỉ bỏ thịt đi; thay vào đó phải thêm nhiều đậu, đậu lăng và các loại hạt vào thực đơn.)" }
    ]
  },
  {
    id: "lesen-mc-6",
    title: "Teil 2: Boom der Online-Supermärkte",
    level: "B1",
    topic: "Konsum & Alltag",
    duration: "15 Phút",
    type: "Trắc nghiệm",
    questionType: "multiple_choice",
    readingText: `Wirtschafts-News: Das Einkaufsverhalten der Deutschen verändert sich dramatisch und dauerhaft. Immer weniger Menschen verbringen ihren kostbaren Samstagvormittag damit, schwere Einkaufswagen durch überfüllte Supermärkte zu schieben. Stattdessen erledigen sie ihren Wocheneinkauf bequem vom heimischen Sofa aus. Der Online-Handel mit Lebensmitteln verzeichnete im letzten Jahr ein rasantes Wachstum von fast 40 Prozent.

Die Vorteile liegen für viele Verbraucher klar auf der Hand: Man spart enorm viel Zeit, muss sich nicht an den endlosen Kassen anstellen und vor allem keine schweren Getränkekisten oder Kartoffelsäcke in den dritten Stock tragen. Die Bestellung erfolgt meist über eine übersichtliche App, und die Lebensmittel werden oft schon am nächsten Tag, in manchen Großstädten sogar innerhalb von nur zwei Stunden, direkt bis an die Wohnungstür geliefert. 

Trotz der großen Beliebtheit hat dieses bequeme System auch offensichtliche Nachteile. Zum einen fallen bei fast jeder Bestellung zusätzliche Liefergebühren an, was den Einkauf insgesamt teurer macht. Zum anderen kritisieren Umweltschützer scharf, dass für die Lieferung extrem viel Verpackungsmüll anfällt – vor allem Kühlakkus und dicke Plastiktüten, um die Frische der Produkte zu garantieren. Außerdem warnen Gewerkschaften vor den harten Arbeitsbedingungen der Lieferanten, die unter enormem Zeitdruck schwere Kisten schleppen müssen und dafür oft nur den gesetzlichen Mindestlohn erhalten. Traditionelle Supermärkte versuchen nun gegenzusteuern, indem sie ihre Geschäfte moderner gestalten und Selbstbedienungskassen einführen.`,
    questions: [
      { id: 1, question: "Was machen laut Text immer weniger Deutsche?", options: ["A) Sie kaufen überhaupt keine Lebensmittel mehr.", "B) Sie gehen am Wochenende in überfüllten Supermärkten einkaufen.", "C) Sie bestellen Lebensmittel über das Internet."], correct: "B) Sie gehen am Wochenende in überfüllten Supermärkten einkaufen.", explanation: "Immer weniger Menschen verbringen ihren kostbaren Samstagvormittag damit, schwere Einkaufswagen durch überfüllte Supermärkte zu schieben. (Ngày càng có ít người dành cả buổi sáng Thứ Bảy quý giá của họ để đẩy chiếc xe hàng nặng nhọc qua các siêu thị đông đúc.)" },
      { id: 2, question: "Welchen Vorteil des Online-Kaufs nennt der Text?", options: ["A) Die Lebensmittel sind online viel frischer.", "B) Man muss sich nicht an der Kasse anstellen und schwere Dinge tragen.", "C) Man bekommt immer kostenlose Geschenke dazu."], correct: "B) Man muss sich nicht an der Kasse anstellen und schwere Dinge tragen.", explanation: "Man spart enorm viel Zeit, muss sich nicht an den endlosen Kassen anstellen und vor allem keine schweren Getränkekisten... tragen. (Người ta tiết kiệm được rất nhiều thời gian, không phải xếp hàng chờ đợi ở các quầy thanh toán dài dằng dặc và đặc biệt là không phải bê vác những thùng đồ uống nặng.)" },
      { id: 3, question: "Wie schnell können die Lieferungen in manchen Großstädten ankommen?", options: ["A) Innerhalb von einer Woche.", "B) In weniger als 15 Minuten.", "C) Innerhalb von nur zwei Stunden."], correct: "C) Innerhalb von nur zwei Stunden.", explanation: "...in manchen Großstädten sogar innerhalb von nur zwei Stunden... (...ở một số thành phố lớn, hàng được giao thậm chí chỉ trong vòng vỏn vẹn hai giờ đồng hồ...)" },
      { id: 4, question: "Was ist ein finanzieller Nachteil für die Kunden beim Online-Kauf?", options: ["A) Sie müssen zusätzliche Liefergebühren bezahlen.", "B) Die Produkte im Online-Shop sind oft doppelt so teuer.", "C) Man kann nur mit teuren Kreditkarten bezahlen."], correct: "A) Sie müssen zusätzliche Liefergebühren bezahlen.", explanation: "Zum einen fallen bei fast jeder Bestellung zusätzliche Liefergebühren an... (Một điểm là gần như mỗi đơn hàng đều phát sinh thêm phụ phí giao hàng...)" },
      { id: 5, question: "Warum kritisieren Umweltschützer die Online-Supermärkte?", options: ["A) Weil die Lieferautos oft im Stau stehen.", "B) Weil für die Frische der Produkte extrem viel Verpackungsmüll (Plastik) entsteht.", "C) Weil sie Lebensmittel wegwerfen, die nicht verkauft wurden."], correct: "B) Weil für die Frische der Produkte extrem viel Verpackungsmüll (Plastik) entsteht.", explanation: "...kritisieren Umweltschützer scharf, dass für die Lieferung extrem viel Verpackungsmüll anfällt – vor allem Kühlakkus und dicke Plastiktüten... (Các nhà bảo vệ môi trường chỉ trích gay gắt rằng việc giao hàng tạo ra quá nhiều rác thải đóng gói - đặc biệt là túi đá giữ lạnh và túi nilon dày...)" },
      { id: 6, question: "Welches Problem haben die Lieferanten (Fahrer)?", options: ["A) Sie finden die Adressen der Kunden oft nicht.", "B) Sie müssen schwere Kisten unter hohem Zeitdruck tragen und verdienen wenig.", "C) Sie müssen die Fahrzeuge selbst kaufen und reparieren."], correct: "B) Sie müssen schwere Kisten unter hohem Zeitdruck tragen und verdienen wenig.", explanation: "...die unter enormem Zeitdruck schwere Kisten schleppen müssen und dafür oft nur den gesetzlichen Mindestlohn erhalten. (...(các tài xế) phải bê các thùng hàng nặng dưới áp lực thời gian khủng khiếp mà thường chỉ nhận được mức lương tối thiểu theo luật định.)" }
    ]
  },
  {
    id: "lesen-mc-7",
    title: "Teil 2: Das Comeback der Schallplatte",
    level: "B1",
    topic: "Kultur & Medien",
    duration: "15 Phút",
    type: "Trắc nghiệm",
    questionType: "multiple_choice",
    readingText: `Kultur & Musik Magazin: Es mag völlig paradox klingen im Zeitalter von Streaming-Diensten wie Spotify und Apple Music, bei denen Millionen von Songs für wenige Euro im Monat jederzeit auf dem Smartphone verfügbar sind: Die klassische Vinyl-Schallplatte feiert seit einigen Jahren ein absolut unerwartetes und gigantisches Comeback. Letztes Jahr wurden in Deutschland erstmals seit 1990 wieder mehr Schallplatten als CDs verkauft. 

Doch wer kauft diese großen, unpraktischen und teuren schwarzen Scheiben? Es sind längst nicht mehr nur ältere Nostalgiker, die sich an ihre Jugend in den 70er Jahren erinnern wollen. Es ist vor allem die junge Generation der 20- bis 30-Jährigen, die die Faszination für das analoge Musikhören entdeckt hat. Für sie ist Musik-Streaming oft zu schnell, zu unsichtbar und zu unpersönlich geworden. 

Viele Musikfans betonen, dass sie beim Hören einer Schallplatte die Musik viel bewusster und intensiver wahrnehmen. Man muss die Platte vorsichtig aus der großen, oft kunstvoll gestalteten Hülle nehmen, sie behutsam auf den Plattenspieler legen und nach etwa 20 Minuten aufstehen, um sie umzudrehen. Man kann Musik nicht einfach nebenbei beim Joggen überspringen. Auch der Klang wird oft gelobt: Experten und Audiophile schwören, dass der warme, leicht kratzige Klang einer analogen Schallplatte der sterilen Perfektion einer digitalen MP3-Datei weit überlegen ist. Für echte Fans ist eine Schallplattensammlung zudem ein wertvolles Hobby und ein optisches Statement im Wohnzimmer.`,
    questions: [
      { id: 1, question: "Welches überraschende musikalische Phänomen wird im Text beschrieben?", options: ["A) Niemand hört mehr Musik über das Internet.", "B) Die Vinyl-Schallplatte wird wieder sehr oft gekauft, sogar mehr als die CD.", "C) Die CD ist in Deutschland so beliebt wie noch nie zuvor."], correct: "B) Die Vinyl-Schallplatte wird wieder sehr oft gekauft, sogar mehr als die CD.", explanation: "Die klassische Vinyl-Schallplatte feiert... ein... Comeback. Letztes Jahr wurden... wieder mehr Schallplatten als CDs verkauft. (Đĩa than cổ điển đang có sự trở lại ngoạn mục. Năm ngoái, số lượng đĩa than được bán ra lại vượt qua đĩa CD.)" },
      { id: 2, question: "Wer kauft heutzutage laut dem Text hauptsächlich Schallplatten?", options: ["A) Nur alte Menschen, die keine Computer bedienen können.", "B) Vor allem junge Menschen zwischen 20 und 30 Jahren.", "C) Ausschließlich professionelle DJs in großen Clubs."], correct: "B) Vor allem junge Menschen zwischen 20 und 30 Jahren.", explanation: "Es ist vor allem die junge Generation der 20- bis 30-Jährigen, die die Faszination... entdeckt hat. (Đó chủ yếu là thế hệ trẻ từ 20 đến 30 tuổi, những người đã khám phá ra sức hấp dẫn...)" },
      { id: 3, question: "Was stört viele junge Fans an Musik-Streaming-Diensten wie Spotify?", options: ["A) Sie sind viel zu teuer im Monat.", "B) Das Musikhören ist zu unsichtbar, zu unpersönlich und zu schnell geworden.", "C) Man findet dort nicht die aktuellen Lieder der Charts."], correct: "B) Das Musikhören ist zu unsichtbar, zu unpersönlich und zu schnell geworden.", explanation: "Für sie ist Musik-Streaming oft zu schnell, zu unsichtbar und zu unpersönlich geworden. (Đối với họ, việc nghe nhạc trực tuyến thường đã trở nên quá vội vã, quá vô hình và quá thiếu dấu ấn cá nhân.)" },
      { id: 4, question: "Was ist laut Text ein bewusster Schritt beim Hören einer Schallplatte?", options: ["A) Man muss nach 20 Minuten aufstehen und die Platte umdrehen.", "B) Man kann die Musik einfach nebenbei beim Joggen hören.", "C) Man muss vorher ein langes Kabel an den Lautsprecher anschließen."], correct: "A) Man muss nach 20 Minuten aufstehen und die Platte umdrehen.", explanation: "...sie behutsam auf den Plattenspieler legen und nach etwa 20 Minuten aufstehen, um sie umzudrehen. (...phải nhẹ nhàng đặt nó lên mâm đĩa than và sau khoảng 20 phút thì đứng dậy để lật mặt đĩa.)" },
      { id: 5, question: "Wie beschreiben Experten den Klang einer Schallplatte?", options: ["A) Er ist sehr laut und nervös.", "B) Er klingt steril und extrem perfekt wie eine CD.", "C) Er klingt warm und leicht kratzig, was von vielen bevorzugt wird."], correct: "C) Er klingt warm und leicht kratzig, was von vielen bevorzugt wird.", explanation: "Experten und Audiophile schwören, dass der warme, leicht kratzige Klang einer analogen Schallplatte der sterilen Perfektion einer digitalen MP3-Datei weit überlegen ist. (Các chuyên gia quả quyết rằng âm thanh ấm áp, hơi xước nhẹ của đĩa than analog vượt trội hơn hẳn so với sự hoàn hảo vô hồn của tệp MP3 kỹ thuật số.)" },
      { id: 6, question: "Welchen weiteren Grund gibt es für das Sammeln von Schallplatten?", options: ["A) Man kann damit sehr schnell sehr reich werden.", "B) Sie sind ein optisches Statement und sehen im Wohnzimmer gut aus.", "C) Man bekommt vom Staat Geld für das Recycling."], correct: "B) Sie sind ein optisches Statement und sehen im Wohnzimmer gut aus.", explanation: "Für echte Fans ist eine Schallplattensammlung zudem ein wertvolles Hobby und ein optisches Statement im Wohnzimmer. (Đối với những người hâm mộ đích thực, bộ sưu tập đĩa than còn là một tuyên ngôn về thẩm mỹ trong phòng khách.)" }
    ]
  },
  {
    id: "lesen-mc-8",
    title: "Teil 2: Das Konzept der Minimalisten",
    level: "B1",
    topic: "Gesellschaft & Lifestyle",
    duration: "15 Phút",
    type: "Trắc nghiệm",
    questionType: "multiple_choice",
    readingText: `Gesellschaft im Wandel: Wie viele Dinge braucht ein Mensch wirklich, um glücklich zu sein? Während die Gesellschaft durch ständige Werbung immer mehr konsumiert, wächst gleichzeitig eine starke Gegenbewegung heran: der sogenannte Minimalismus. Anhänger dieses extremen Lifestyles versuchen ganz bewusst, mit so wenig materiellen Besitztümern wie möglich auszukommen. Einige Hardcore-Minimalisten besitzen oft nicht mehr als exakt 100 Dinge insgesamt – inklusive ihrer gesamten Kleidung, Möbel und Bücher.

Für die meisten geht es beim Minimalismus jedoch gar nicht um eine genaue Zahl, sondern vielmehr um eine grundlegende Philosophie. Sie möchten sich einfach von unnötigem Ballast befreien. Ein aufgeräumtes, fast leeres Zimmer bedeutet für sie auch einen aufgeräumten, klaren Geist. Anstatt ihr hart verdientes Geld für das neueste Smartphone, teure Markenkleidung oder Dekoration auszugeben, investieren Minimalisten ihr Geld lieber in Erlebnisse: in ausgedehnte Reisen, Museumsbesuche, gutes Essen mit Freunden oder Weiterbildungskurse. 

Psychologen, die diesen Trend analysiert haben, sehen darin eine verständliche Reaktion auf unsere extrem hektische, reizüberflutete moderne Welt. Wenn man sich nicht ständig darum kümmern muss, Dinge zu kaufen, zu putzen, zu reparieren oder zu organisieren, hat man am Ende des Tages deutlich mehr freie Zeit für das Wesentliche im Leben. Kritiker, oft aus der Wirtschaft, merken jedoch an, dass nicht jeder Mensch minimalistisch leben kann; Familien mit kleinen Kindern beispielsweise brauchen naturgemäß mehr Platz und mehr Dinge, und ein massenhafter Konsumverzicht würde viele Arbeitsplätze in der Produktion gefährden.`,
    questions: [
      { id: 1, question: "Was ist das Hauptziel der Minimalismus-Bewegung?", options: ["A) So viele teure Dinge wie möglich zu besitzen.", "B) Mit so wenig materiellen Besitztümern wie möglich zu leben.", "C) Niemals wieder in einem normalen Geschäft einzukaufen."], correct: "B) Mit so wenig materiellen Besitztümern wie möglich zu leben.", explanation: "Anhänger dieses extremen Lifestyles versuchen ganz bewusst, mit so wenig materiellen Besitztümern wie möglich auszukommen. (Những người theo đuổi phong cách sống này chủ động cố gắng xoay xở với càng ít của cải vật chất càng tốt.)" },
      { id: 2, question: "Wie viele Dinge besitzen einige extreme 'Hardcore-Minimalisten'?", options: ["A) Ungefähr 1000 Dinge.", "B) Oft nicht mehr als exakt 100 Dinge insgesamt.", "C) Gar keine Dinge, sie leben auf der Straße."], correct: "B) Oft nicht mehr als exakt 100 Dinge insgesamt.", explanation: "Einige Hardcore-Minimalisten besitzen oft nicht mehr als exakt 100 Dinge insgesamt... (Một số người theo chủ nghĩa tối giản hạng nặng thường sở hữu tổng cộng không quá đúng 100 món đồ...)" },
      { id: 3, question: "Wofür geben Minimalisten ihr Geld lieber aus als für Gegenstände?", options: ["A) Sie sparen alles auf dem Bankkonto für das Alter.", "B) Für teure und seltene Autos.", "C) Für Erlebnisse wie Reisen, gutes Essen und Weiterbildung."], correct: "C) Für Erlebnisse wie Reisen, gutes Essen und Weiterbildung.", explanation: "...investieren Minimalisten ihr Geld lieber in Erlebnisse: in ausgedehnte Reisen, Museumsbesuche, gutes Essen... (...những người tối giản thích đầu tư tiền của họ vào các trải nghiệm hơn: những chuyến du lịch dài ngày, thăm bảo tàng, ăn ngon...)" },
      { id: 4, question: "Wie erklären Psychologen diesen Trend zum Minimalismus?", options: ["A) Es ist eine Reaktion auf unsere hektische, reizüberflutete moderne Welt.", "B) Die Leute haben heute einfach weniger Geld als früher.", "C) Die Menschen sind zu faul geworden, um einkaufen zu gehen."], correct: "A) Es ist eine Reaktion auf unsere hektische, reizüberflutete moderne Welt.", explanation: "Psychologen... sehen darin eine verständliche Reaktion auf unsere extrem hektische, reizüberflutete moderne Welt. (Các nhà tâm lý học... coi đây là một phản ứng dễ hiểu đối với thế giới hiện đại cực kỳ hối hả và quá tải thông tin của chúng ta.)" },
      { id: 5, question: "Was ist ein Vorteil davon, wenige Dinge zu besitzen?", options: ["A) Man bekommt Lob von den Nachbarn.", "B) Man muss weniger Zeit mit Putzen und Reparieren verbringen.", "C) Man kann die Wohnung viel teurer weitervermieten."], correct: "B) Man muss weniger Zeit mit Putzen und Reparieren verbringen.", explanation: "Wenn man sich nicht ständig darum kümmern muss, Dinge zu... putzen, zu reparieren... hat man am Ende des Tages deutlich mehr freie Zeit... (Nếu bạn không phải liên tục bận tâm đến việc dọn dẹp, sửa chữa đồ đạc... bạn sẽ có nhiều thời gian rảnh rỗi hơn vào cuối ngày.)" },
      { id: 6, question: "Welches Gegenargument bringen Kritiker der Bewegung an?", options: ["A) Ein Verzicht auf Konsum könnte Arbeitsplätze in der Wirtschaft gefährden.", "B) Minimalisten sind oft sehr unfreundlich zu anderen Menschen.", "C) Wohnungen ohne Möbel sehen zu langweilig aus."], correct: "A) Ein Verzicht auf Konsum könnte Arbeitsplätze in der Wirtschaft gefährden.", explanation: "Kritiker... merken jedoch an... dass... ein massenhafter Konsumverzicht... viele Arbeitsplätze in der Produktion gefährden (würde). (Các nhà phê bình chỉ ra rằng việc tẩy chay tiêu dùng hàng loạt sẽ đe dọa đến nhiều việc làm trong ngành sản xuất.)" }
    ]
  },
  {
    id: "lesen-mc-9",
    title: "Teil 2: Urban Gardening – Gärtnern in der Stadt",
    level: "B1",
    topic: "Natur & Stadtleben",
    duration: "15 Phút",
    type: "Trắc nghiệm",
    questionType: "multiple_choice",
    readingText: `Stadtmagazin: Ein Spaziergang durch Berlin, Köln oder Leipzig offenbart einen faszinierenden neuen Trend, der das graue Stadtbild zunehmend grün färbt: das sogenannte "Urban Gardening". Mitten in der dicht bebauten Stadt, oft auf verlassenen Industriebrachen, zwischen Hochhäusern oder sogar hoch oben auf den flachen Dächern von Parkhäusern, entstehen plötzlich kleine, blühende Gemüsegärten. 

Anwohner, Nachbarn und engagierte Studenten treffen sich dort nach Feierabend, um gemeinsam in großen Holzkisten Karotten, Tomaten, Kräuter und sogar kleine Kürbisse anzupflanzen. Das Hauptziel dieses Phänomens ist jedoch für die meisten Teilnehmer nicht in erster Linie die finanzielle Ersparnis beim Einkaufen von Lebensmitteln. Vielmehr geht es um das starke Gemeinschaftsgefühl und die soziale Interaktion. Menschen aus völlig unterschiedlichen Kulturen und Altersgruppen kommen beim gemeinsamen Graben und Gießen ins Gespräch. Außerdem lernen Stadtkinder, die oft glauben, dass Gemüse in Plastikfolie in der Fabrik hergestellt wird, wie eine Pflanze vom Samen bis zur Ernte tatsächlich wächst.

Darüber hinaus hat Urban Gardening viele sehr positive Auswirkungen auf das städtische Klima. Die vielen Pflanzen produzieren wertvollen Sauerstoff, bieten wichtigen Insekten wie Bienen und Schmetterlingen einen sicheren Lebensraum und helfen sogar, die Luft in den stark befahrenen Straßen abzukühlen. Die Stadtverwaltungen haben die enormen Vorteile längst erkannt und unterstützen diese Projekte mittlerweile oft, indem sie öffentliche Flächen kostenlos zur Verfügung stellen und den Zugang zu Wasseranschlüssen erleichtern.`,
    questions: [
      { id: 1, question: "Wo genau findet das 'Urban Gardening' statt?", options: ["A) Nur auf großen Bauernhöfen weit außerhalb der Stadt.", "B) Mitten in der Stadt, z.B. auf Dächern oder alten Industrieflächen.", "C) Ausschließlich in den privaten Gärten von reichen Leuten."], correct: "B) Mitten in der Stadt, z.B. auf Dächern oder alten Industrieflächen.", explanation: "Mitten in der dicht bebauten Stadt, oft auf verlassenen Industriebrachen... oder sogar hoch oben auf den flachen Dächern... (Nằm ngay giữa lòng thành phố đông đúc, thường là trên các khu công nghiệp bỏ hoang... hoặc thậm chí trên cao ở nóc các bãi đỗ xe...)" },
      { id: 2, question: "Warum machen viele Menschen beim Urban Gardening mit?", options: ["A) Sie wollen ihr eigenes Gemüse auf dem Markt verkaufen, um reich zu werden.", "B) Sie suchen das Gemeinschaftsgefühl und möchten andere Menschen treffen.", "C) Sie werden von der Stadt dazu verpflichtet."], correct: "B) Sie suchen das Gemeinschaftsgefühl und möchten andere Menschen treffen.", explanation: "Vielmehr geht es um das starke Gemeinschaftsgefühl und die soziale Interaktion. (Đúng hơn thì, điều quan trọng nhất là tinh thần cộng đồng mạnh mẽ và sự tương tác xã hội.)" },
      { id: 3, question: "Was ist ein wichtiger Lerneffekt für Stadtkinder durch diese Gärten?", options: ["A) Sie lernen, wie man teures Werkzeug richtig repariert.", "B) Sie lernen, woher das Gemüse kommt und wie es in der Natur wächst.", "C) Sie lernen, wie man Kisten aus Holz baut."], correct: "B) Sie lernen, woher das Gemüse kommt und wie es in der Natur wächst.", explanation: "Außerdem lernen Stadtkinder... wie eine Pflanze vom Samen bis zur Ernte tatsächlich wächst. (Bên cạnh đó, trẻ em thành phố cũng được học cách một cái cây thực sự lớn lên từ hạt giống cho đến lúc thu hoạch như thế nào.)" },
      { id: 4, question: "Welchen positiven Effekt haben die kleinen Gärten auf die Tierwelt?", options: ["A) Vögel finden mehr Platz zum Schlafen.", "B) Straßenhunde finden dort Futter.", "C) Insekten wie Bienen finden dort einen sicheren Lebensraum."], correct: "C) Insekten wie Bienen finden dort einen sicheren Lebensraum.", explanation: "Die vielen Pflanzen... bieten wichtigen Insekten wie Bienen... einen sicheren Lebensraum... (Rất nhiều cây cối... cung cấp không gian sống an toàn cho các loài côn trùng quan trọng như ong...)" },
      { id: 5, question: "Wie verändern die Gärten das Klima in der Stadt?", options: ["A) Sie machen die Straßenluft wärmer.", "B) Sie helfen dabei, die Luft in der Umgebung abzukühlen.", "C) Sie sorgen für viel mehr Regen im Sommer."], correct: "B) Sie helfen dabei, die Luft in der Umgebung abzukühlen.", explanation: "...und helfen sogar, die Luft in den stark befahrenen Straßen abzukühlen. (...và thậm chí giúp làm mát không khí ở những con phố có mật độ giao thông cao.)" },
      { id: 6, question: "Wie reagieren die Stadtverwaltungen auf diese Entwicklung?", options: ["A) Sie verbieten die Gärten, weil sie unordentlich aussehen.", "B) Sie verlangen hohe Steuern für den Anbau von Tomaten.", "C) Sie unterstützen die Projekte oft mit kostenlosen Flächen und Wasser."], correct: "C) Sie unterstützen die Projekte oft mit kostenlosen Flächen und Wasser.", explanation: "Die Stadtverwaltungen... unterstützen diese Projekte mittlerweile oft, indem sie öffentliche Flächen kostenlos zur Verfügung stellen und den Zugang zu Wasser... (Chính quyền thành phố thường ủng hộ các dự án này bằng cách cung cấp không gian công cộng miễn phí và lối lấy nước...)" }
    ]
  },
  {
    id: "lesen-mc-10",
    title: "Teil 2: Leben im Tiny House",
    level: "B1",
    topic: "Wohnen & Lifestyle",
    duration: "15 Phút",
    type: "Trắc nghiệm",
    questionType: "multiple_choice",
    readingText: `Wohnmagazin: Immer mehr Menschen in Deutschland träumen von einem radikal anderen Lebensstil. Sie verlassen ihre großen Wohnungen oder Einfamilienhäuser und ziehen stattdessen in sogenannte "Tiny Houses" – das sind winzige, voll ausgestattete Häuser, die oft nur zwischen 15 und maximal 35 Quadratmeter groß sind. Häufig sind diese Mini-Häuser sogar auf einem Anhänger aufgebaut, sodass man sie mit einem starken Auto überallhin bewegen kann.

Ein großer Vorteil dieser Wohnform liegt natürlich bei den stark reduzierten Kosten. Wer in einem Tiny House lebt, braucht keinen teuren Kredit über 30 Jahre bei der Bank aufzunehmen und spart jeden Monat hunderte Euro bei Heizung, Strom und Wasser. Viele Bewohner berichten, dass sie dadurch die finanzielle Freiheit gewonnen haben, weniger arbeiten zu müssen und mehr Zeit für ihre Hobbys aufbringen zu können. Zudem zwingt der extrem begrenzte Platz dazu, nur Dinge zu behalten, die man wirklich regelmäßig braucht. 

Allerdings ist der Traum vom winzigen Haus in Deutschland mit vielen bürokratischen Hürden verbunden. Man darf sein Tiny House nicht einfach irgendwo auf eine schöne, grüne Wiese oder an einen See stellen. Das deutsche Baurecht ist streng: Man benötigt ein offizielles Grundstück, das erschlossen ist, also Anschlüsse für Wasser, Abwasser und Strom hat, und eine aufwendige Baugenehmigung. Dies ist oft teurer und komplizierter als der Bau des kleinen Hauses selbst. Für Familien mit mehreren Kindern ist das Tiny House auf Dauer ohnehin meist keine praktische Lösung, da es an Privatsphäre fehlt.`,
    questions: [
      { id: 1, question: "Was ist ein 'Tiny House' laut dem Artikel?", options: ["A) Ein großes, altes Bauernhaus auf dem Land.", "B) Ein winziges Haus, das meist nur 15 bis 35 Quadratmeter groß ist.", "C) Ein Zelt, das man auf einem Campingplatz aufbauen kann."], correct: "B) Ein winziges Haus, das meist nur 15 bis 35 Quadratmeter groß ist.", explanation: "...das sind winzige, voll ausgestattete Häuser, die oft nur zwischen 15 und maximal 35 Quadratmeter groß sind. (...đó là những ngôi nhà siêu nhỏ, trang bị đầy đủ tiện nghi, thường chỉ rộng từ 15 đến tối đa 35 mét vuông.)" },
      { id: 2, question: "Warum sind Tiny Houses oft sehr mobil?", options: ["A) Weil sie sehr leicht sind und man sie tragen kann.", "B) Weil man sie einfach in Einzelteile zerlegen und per Post verschicken kann.", "C) Weil sie häufig auf einem Anhänger gebaut sind und von Autos gezogen werden können."], correct: "C) Weil sie häufig auf einem Anhänger gebaut sind und von Autos gezogen werden können.", explanation: "Häufig sind diese Mini-Häuser sogar auf einem Anhänger aufgebaut, sodass man sie mit einem starken Auto überallhin bewegen kann. (Nhiều khi những ngôi nhà mini này còn được dựng trên rơ-moóc để người ta có thể dùng ô tô khỏe kéo nó đi khắp nơi.)" },
      { id: 3, question: "Welchen großen Vorteil bietet das Wohnen in einem Tiny House?", options: ["A) Man spart sehr viel Geld bei den Bau- und Nebenkosten.", "B) Man kann unglaublich viele Möbel und Kleidung darin lagern.", "C) Man bekommt vom Staat Geld für den Bau geschenkt."], correct: "A) Man spart sehr viel Geld bei den Bau- und Nebenkosten.", explanation: "Wer in einem Tiny House lebt, braucht keinen teuren Kredit... und spart jeden Monat hunderte Euro bei Heizung, Strom und Wasser. (Ai sống trong Tiny House sẽ không phải vay khoản tín dụng đắt đỏ... và mỗi tháng tiết kiệm được hàng trăm Euro tiền sưởi, điện, nước.)" },
      { id: 4, question: "Was ist ein positiver Effekt der finanziellen Freiheit für die Bewohner?", options: ["A) Sie können mehr teure Autos kaufen.", "B) Sie müssen oft weniger arbeiten und haben mehr Zeit für Hobbys.", "C) Sie reisen jedes Jahr monatelang um die Welt."], correct: "B) Sie müssen oft weniger arbeiten und haben mehr Zeit für Hobbys.", explanation: "Viele Bewohner berichten, dass sie dadurch die finanzielle Freiheit gewonnen haben, weniger arbeiten zu müssen und mehr Zeit für ihre Hobbys aufbringen zu können. (Nhiều cư dân chia sẻ nhờ đó họ có tự do tài chính để làm việc ít đi và có nhiều thời gian cho sở thích cá nhân hơn.)" },
      { id: 5, question: "Welches Problem gibt es mit Tiny Houses speziell in Deutschland?", options: ["A) Das strenge Baurecht macht es schwer, einen legalen Platz dafür zu finden.", "B) Es gibt keine Firmen in Deutschland, die solche Häuser bauen.", "C) Das Klima ist zu kalt, um in so einem Haus zu überleben."], correct: "A) Das strenge Baurecht macht es schwer, einen legalen Platz dafür zu finden.", explanation: "Allerdings ist der Traum... in Deutschland mit vielen bürokratischen Hürden verbunden... Das deutsche Baurecht ist streng: Man benötigt ein offizielles Grundstück... und eine aufwendige Baugenehmigung. (Tuy nhiên, giấc mơ này ở Đức đi kèm với nhiều rào cản hành chính... Luật xây dựng ở Đức rất nghiêm ngặt: bạn cần một mảnh đất chính thức... và giấy phép xây dựng phức tạp.)" },
      { id: 6, question: "Für wen ist das Wohnen in einem Mini-Haus auf Dauer oft ungeeignet?", options: ["A) Für alleinstehende Rentner.", "B) Für Familien mit mehreren Kindern wegen fehlender Privatsphäre.", "C) Für junge Studenten."], correct: "B) Für Familien mit mehreren Kindern wegen fehlender Privatsphäre.", explanation: "Für Familien mit mehreren Kindern ist das Tiny House auf Dauer ohnehin meist keine praktische Lösung, da es an Privatsphäre fehlt. (Đối với các gia đình có nhiều con, Tiny House về lâu dài thường không phải là giải pháp thiết thực vì thiếu sự riêng tư.)" }
    ]
  }
];
